name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: IsaacOrzDev/demo-system-overview/.github/workflows/reusable_aws_deployment.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      repository_name: demo-system-api
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_ROLE_ARN_FOR_ECS: ${{ secrets.AWS_ROLE_ARN_FOR_ECS }}
